/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Block List
 * The block list API description
 * OpenAPI spec version: 1.0
 */
import { createInstance } from './api-instance';
import type { BodyType } from './api-instance';
export type BlockListControllerGetListParams = {
  q?: string;
};

export type AddBlockItemDtoType =
  (typeof AddBlockItemDtoType)[keyof typeof AddBlockItemDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddBlockItemDtoType = {
  KeyWord: 'KeyWord',
  Website: 'Website',
} as const;

export interface AddBlockItemDto {
  data: string;
  type: AddBlockItemDtoType;
}

export type BlockItemDtoType =
  (typeof BlockItemDtoType)[keyof typeof BlockItemDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockItemDtoType = {
  KeyWord: 'KeyWord',
  Website: 'Website',
} as const;

export interface BlockItemDto {
  blockListId: number;
  createdAt: string;
  data: string;
  id: number;
  type: BlockItemDtoType;
}

export interface BlockListDto {
  id: number;
  items: BlockItemDto[];
  ownerId: number;
}

export interface PatchAccountDto {
  isBlockingEnabled?: boolean;
}

export interface AccountDto {
  id: number;
  isBlockingEnabled: boolean;
  ownerId: number;
}

export interface GetSessionInfoDto {
  email: string;
  exp: number;
  iat: number;
  id: number;
}

export interface SignInBodyDto {
  email: string;
  password: string;
}

export interface SignUpBodyDto {
  email: string;
  password: string;
}

/**
 * Создается пользователь, его аккаунт и список блокировок
 * @summary Регистрация
 */
export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
) => {
  return createInstance<void>({
    url: `/auth/sign-up`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: signUpBodyDto,
  });
};

/**
 * @summary Авторизация
 */
export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
) => {
  return createInstance<void>({
    url: `/auth/sign-in`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: signInBodyDto,
  });
};

/**
 * @summary Выход
 */
export const authControllerSignOut = () => {
  return createInstance<void>({ url: `/auth/sign-out`, method: 'POST' });
};

/**
 * @summary Получить сессию пользователя
 */
export const authControllerGetSessionInfo = () => {
  return createInstance<GetSessionInfoDto>({
    url: `/auth/session`,
    method: 'GET',
  });
};

/**
 * @summary Получить данные
 */
export const accountControllerGetAccount = () => {
  return createInstance<AccountDto>({ url: `/account`, method: 'GET' });
};

/**
 * @summary Обновить данные
 */
export const accountControllerPatchAccount = (
  patchAccountDto: BodyType<PatchAccountDto>,
) => {
  return createInstance<AccountDto>({
    url: `/account`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: patchAccountDto,
  });
};

/**
 * @summary Получить все записи блокировок
 */
export const blockListControllerGetList = (
  params?: BlockListControllerGetListParams,
) => {
  return createInstance<BlockListDto>({
    url: `/block-list`,
    method: 'GET',
    params,
  });
};

/**
 * @summary Добавить блокировку
 */
export const blockListControllerAddBlockItem = (
  addBlockItemDto: BodyType<AddBlockItemDto>,
) => {
  return createInstance<BlockItemDto>({
    url: `/block-list/item`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addBlockItemDto,
  });
};

/**
 * @summary Удалить блокировку
 */
export const blockListControllerRemoveBlockItem = (id: number) => {
  return createInstance<BlockItemDto>({
    url: `/block-list/item/${id}`,
    method: 'DELETE',
  });
};

export type AuthControllerSignUpResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignInResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;
export type AuthControllerGetSessionInfoResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AccountControllerGetAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerPatchAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>
>;
export type BlockListControllerGetListResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerGetList>>
>;
export type BlockListControllerAddBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerAddBlockItem>>
>;
export type BlockListControllerRemoveBlockItemResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>
>;
